# https://docs.travis-ci.com/user/languages/ruby/
# https://docs.travis-ci.com/user/deployment/rubygems/

language: ruby
sudo: false
cache: bundler
rvm:
  - jruby
  - 2.3.0
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key: "YOUR API KEY"
  on:
    tags: true
    branch!g : master
notifications:
  email:
    recipients:
      - htmldrum@tutanota.com
    on_failure: change
    on_success: never